# Generated by Django 4.1.2 on 2022-11-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0009_manageproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageProduct',
        ),
    ]
