# Generated by Django 4.1.2 on 2022-11-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0010_delete_manageproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellClothes.product')),
            ],
        ),
    ]
