# Generated by Django 4.1.2 on 2022-11-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0011_manageproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageproduct',
            name='product',
        ),
    ]
