# Generated by Django 4.1.2 on 2022-11-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0012_remove_manageproduct_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageProduct',
        ),
    ]
