# Generated by Django 4.1.2 on 2022-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0013_delete_manageproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
