# Generated by Django 4.1.2 on 2022-11-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0014_manageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageproduct',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SellClothes.product'),
        ),
        migrations.AddField(
            model_name='manageproduct',
            name='quantity',
            field=models.IntegerField(default=200),
        ),
    ]
