# Generated by Django 4.1.2 on 2022-11-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0015_manageproduct_name_manageproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageproduct',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellClothes.product'),
        ),
    ]
