# Generated by Django 4.1.2 on 2022-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0016_alter_manageproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=200),
        ),
        migrations.DeleteModel(
            name='ManageProduct',
        ),
    ]
