# Generated by Django 4.1.2 on 2022-12-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0018_product_discount_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_import',
            field=models.IntegerField(default=0, verbose_name='Số lượng mới nhập'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_sale',
            field=models.IntegerField(default=0, verbose_name='Số lượng đã bán'),
        ),
    ]
