# Generated by Django 4.1.2 on 2022-12-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0019_product_quantity_import_product_quantity_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Loại sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Khách hàng đăng ký'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Sản phẩm'},
        ),
    ]
