# Generated by Django 4.1.2 on 2022-12-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0020_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'large')], default='', max_length=200, null=True, verbose_name='Size'),
        ),
    ]
