# Generated by Django 4.1.2 on 2022-12-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0023_order_size_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='M', max_length=10, null=True, verbose_name='Size'),
        ),
    ]
