# Generated by Django 4.1.2 on 2022-12-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0024_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Ngày sửa đổi'),
        ),
    ]
