# Generated by Django 4.1.2 on 2022-12-06 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0026_customer_date_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Ngày thay đổi'),
        ),
    ]
