# Generated by Django 4.1.2 on 2022-12-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0028_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method_pay',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Phương thức thanh toán'),
        ),
    ]
