# Generated by Django 4.1.2 on 2022-12-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0030_alter_order_method_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method_pay',
            field=models.CharField(blank=True, default='Thanh toán khi nhận hàng', max_length=30, null=True, verbose_name='Phương thức thanh toán'),
        ),
    ]
