# Generated by Django 4.1.2 on 2022-12-13 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0032_alter_order_method_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quality', models.CharField(blank=True, default='', max_length=100, verbose_name='Chất lượng sản phẩm')),
                ('service_qualitty', models.CharField(blank=True, default='', max_length=100, verbose_name='Chất lượng dịch vụ')),
                ('transport_quanlity', models.CharField(blank=True, default='', max_length=100, verbose_name='Chất lượng vận chuyển')),
                ('satisfaction_level', models.CharField(blank=True, default='', max_length=100, verbose_name='Mức độ hài lòng')),
                ('commets_other', models.CharField(blank=True, default='', max_length=100, verbose_name='Ý kiến khác')),
                ('date_cmt', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày phản hồi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellClothes.customer', verbose_name='Khách hàng phản hồi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellClothes.product', verbose_name='Sản phẩm phản hồi')),
            ],
            options={
                'verbose_name_plural': 'Phản hồi',
            },
        ),
    ]
