# Generated by Django 4.1.2 on 2022-12-13 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0033_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_cmt',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Thời gian phản hồi'),
        ),
    ]
