# Generated by Django 4.1.2 on 2022-12-13 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0034_comment_time_cmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_cmt',
            field=models.TimeField(default=datetime.datetime.today, verbose_name='Thời gian phản hồi'),
        ),
    ]
