# Generated by Django 4.1.2 on 2022-12-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0036_alter_comment_date_cmt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Phản hồi khách hàng'},
        ),
    ]
