# Generated by Django 4.1.2 on 2022-12-15 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0037_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time_register',
            field=models.TimeField(default=datetime.datetime.today, verbose_name='Thời gian đăng ký'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.datetime.today, verbose_name='Thời gian đặt'),
        ),
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.TimeField(default=datetime.datetime.today, verbose_name='Thời gian đặt cuối'),
        ),
    ]
