# Generated by Django 4.1.2 on 2022-12-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0038_customer_time_register_order_time_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commets_other',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Ý kiến khác'),
        ),
    ]
