# Generated by Django 4.1.2 on 2023-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0040_alter_product_date_alter_product_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricesize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Khoảng giá sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Khoảng giá sản phẩm',
            },
        ),
    ]
