# Generated by Django 4.1.2 on 2023-11-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellClothes', '0043_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='SellClothes.customer'),
        ),
    ]
